import Document, { Html, Head, Main, NextScript } from 'next/document';
import { Inter } from '@next/font/google';

export default class MyDocument extends Document {
  render() {
    return (
      <Html lang='en'>
        <Head>
        </Head>
        <body className={inter.className}>{this.props.children}</body>
        <NextScript />
      </Html>
    )
  }
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
